[workspace]
members = [
    "bins/revme",
    "bins/revm-test",
    "crates/revm",
    "crates/primitives",
    "crates/interpreter",
    "crates/precompile",
]
resolver = "2"
default-members = ["crates/revm"]

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.release]
lto = true
codegen-units = 1
debug = true

[profile.ethtests]
inherits = "test"
opt-level = 3

[patch.crates-io]
# alloy-core = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "e9f2685c" }
# alloy-dyn-abi = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "e9f2685c" }
# alloy-json-abi = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "e9f2685c" }
alloy-primitives = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "e9f2685c" }
alloy-sol-macro = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "e9f2685c" }
alloy-sol-macro-expander = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "e9f2685c" }
alloy-sol-macro-input = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "e9f2685c" }
alloy-sol-types = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "e9f2685c" }
# alloy-sol-type-parser = { git = "ssh://git@github.com/SeismicSystems/seismic-alloy-core.git", rev = "e9f2685c" }

# alloy-core = { path = "../seismic-alloy-core/crates/core" }
# # alloy-dyn-abi = { path = "../seismic-alloy-core/crates/dyn-abi" }
# alloy-json-abi = { path = "../seismic-alloy-core/crates/json-abi" }
# alloy-primitives = { path = "../seismic-alloy-core/crates/primitives" }
# alloy-sol-macro = { path = "../seismic-alloy-core/crates/sol-macro" }
# alloy-sol-macro-expander = { path = "../seismic-alloy-core/crates/sol-macro-expander" }
# alloy-sol-macro-input = { path = "../seismic-alloy-core/crates/sol-macro-input" }
# alloy-sol-types = { path = "../seismic-alloy-core/crates/sol-types" }
# alloy-sol-type-parser = { path = "../seismic-alloy-core/crates/sol-type-parser" }
